# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npx lerna bootstrap
      - run: cd apps/api && yarn test

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install yarn
      - run: yarn add now@13
      - run: chmod -R 777 ./scripts/deploy.sh
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build